export type TravelStyle = 'beach' | 'city' | 'adventure' | 'culture'

export type Continent = 'Europe' | 'Africa' | 'Asia' | 'Americas' | 'Oceania' | 'Middle East'

export type VisaRequirement = 'free' | 'on-arrival' | 'required'

export interface Coordinates {
  lat: number
  lng: number
}

export interface EstimatedCosts {
  /** Round-trip flight estimate in USD per person from a typical European hub */
  flightFromEurope: number
  /** Average hotel cost per night in USD */
  hotelPerNight: number
  /** Daily spending per person in USD (food, transport, activities) */
  dailySpending: number
}

export interface Destination {
  id: string
  name: string
  country: string
  /** ISO 3166-1 alpha-2 country code */
  countryCode: string
  coordinates: Coordinates
  continent: Continent
  description: string
  /** Primary climate type */
  climate: string
  travelStyles: TravelStyle[]
  /** Months (1–12) when this destination is at its best */
  bestMonths: number[]
  estimatedCosts: EstimatedCosts
  activities: string[]
  currency: string
  visa: VisaRequirement
}

export const destinations: Destination[] = [
  // ── Europe ──────────────────────────────────────────────────────────────────
  {
    id: 'barcelona-spain',
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    continent: 'Europe',
    description:
      'A vibrant coastal city famous for Gaudí architecture, golden beaches, and electrifying nightlife.',
    climate: 'mediterranean',
    travelStyles: ['beach', 'city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 120, hotelPerNight: 110, dailySpending: 80 },
    activities: [
      'Sagrada Família',
      'Gothic Quarter',
      'La Barceloneta beach',
      'Park Güell',
      'Camp Nou',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'santorini-greece',
    name: 'Santorini',
    country: 'Greece',
    countryCode: 'GR',
    coordinates: { lat: 36.3932, lng: 25.4615 },
    continent: 'Europe',
    description:
      'An iconic Greek island with whitewashed villages perched on volcanic cliffs above a deep-blue caldera.',
    climate: 'mediterranean',
    travelStyles: ['beach', 'culture'],
    bestMonths: [5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 200, hotelPerNight: 180, dailySpending: 90 },
    activities: ['Oia sunset', 'caldera boat tour', 'wine tasting', 'Red Beach', 'Akrotiri ruins'],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'prague-czech-republic',
    name: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    continent: 'Europe',
    description:
      'The golden city of a hundred spires — a fairy-tale medieval centre with world-class craft beer.',
    climate: 'continental',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 80, hotelPerNight: 70, dailySpending: 50 },
    activities: [
      'Old Town Square',
      'Charles Bridge',
      'Prague Castle',
      'Josefov',
      'Czech beer tasting',
    ],
    currency: 'CZK',
    visa: 'free',
  },
  {
    id: 'amsterdam-netherlands',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    continent: 'Europe',
    description:
      'Canals, cycling culture, world-class museums, and legendary nightlife in a perfectly compact city.',
    climate: 'temperate',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 7, 8, 9],
    estimatedCosts: { flightFromEurope: 90, hotelPerNight: 130, dailySpending: 85 },
    activities: [
      'Rijksmuseum',
      'Van Gogh Museum',
      'canal boat tour',
      'Vondelpark',
      'Anne Frank House',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'lisbon-portugal',
    name: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    coordinates: { lat: 38.7169, lng: -9.1395 },
    continent: 'Europe',
    description:
      'Hilly, sun-drenched Lisbon enchants with trams, azulejo tiles, fado music, and excellent seafood.',
    climate: 'mediterranean',
    travelStyles: ['city', 'culture'],
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 90, dailySpending: 65 },
    activities: [
      'Belém Tower',
      'Alfama district',
      'Jerónimos Monastery',
      'tram 28',
      'Pastéis de Nata',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'rome-italy',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    continent: 'Europe',
    description:
      'The Eternal City — two millennia of art, architecture, and incredible food at every turn.',
    climate: 'mediterranean',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 110, hotelPerNight: 120, dailySpending: 80 },
    activities: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Pantheon', 'Trastevere dinner'],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'dubrovnik-croatia',
    name: 'Dubrovnik',
    country: 'Croatia',
    countryCode: 'HR',
    coordinates: { lat: 42.6507, lng: 18.0944 },
    continent: 'Europe',
    description:
      'The "Pearl of the Adriatic" — a walled medieval city on turquoise waters with dramatic sea views.',
    climate: 'mediterranean',
    travelStyles: ['beach', 'culture', 'city'],
    bestMonths: [5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 150, hotelPerNight: 120, dailySpending: 70 },
    activities: [
      'Old Town walls',
      'Lokrum Island',
      'cable car',
      'sea kayaking',
      'Game of Thrones tour',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'vienna-austria',
    name: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    coordinates: { lat: 48.2082, lng: 16.3738 },
    continent: 'Europe',
    description:
      "Imperial grandeur meets coffee house culture — Vienna is Europe's most refined capital.",
    climate: 'continental',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 120, dailySpending: 80 },
    activities: [
      'Schönbrunn Palace',
      'Kunsthistorisches Museum',
      'Opera House',
      'Naschmarkt',
      'Café Central',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'edinburgh-uk',
    name: 'Edinburgh',
    country: 'United Kingdom',
    countryCode: 'GB',
    coordinates: { lat: 55.9533, lng: -3.1883 },
    continent: 'Europe',
    description:
      "Scotland's dramatic capital perches on volcanic rock — a city of medieval closes, festivals, and whisky.",
    climate: 'oceanic',
    travelStyles: ['city', 'culture', 'adventure'],
    bestMonths: [5, 6, 7, 8, 9],
    estimatedCosts: { flightFromEurope: 80, hotelPerNight: 110, dailySpending: 70 },
    activities: [
      'Edinburgh Castle',
      'Royal Mile',
      "Arthur's Seat hike",
      'Scotch whisky trail',
      'Fringe Festival',
    ],
    currency: 'GBP',
    visa: 'free',
  },
  {
    id: 'paris-france',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    continent: 'Europe',
    description: 'The City of Light — romance, art, fashion, and the finest cuisine on the planet.',
    climate: 'temperate',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 160, dailySpending: 100 },
    activities: ['Eiffel Tower', 'Louvre', 'Montmartre', 'Seine river cruise', 'Versailles'],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'amalfi-coast-italy',
    name: 'Amalfi Coast',
    country: 'Italy',
    countryCode: 'IT',
    coordinates: { lat: 40.6333, lng: 14.6029 },
    continent: 'Europe',
    description:
      'Vertiginous cliff roads, lemon groves, and pastel villages cascading to a cobalt-blue sea.',
    climate: 'mediterranean',
    travelStyles: ['beach', 'adventure', 'culture'],
    bestMonths: [5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 120, hotelPerNight: 150, dailySpending: 90 },
    activities: [
      'boat trip',
      'Path of the Gods hike',
      'Positano',
      'limoncello tasting',
      'Ravello gardens',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'reykjavik-iceland',
    name: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    coordinates: { lat: 64.1466, lng: -21.9426 },
    continent: 'Europe',
    description:
      'Gateway to the midnight sun, Northern Lights, geysers, glaciers, and dramatic volcanic landscapes.',
    climate: 'subarctic',
    travelStyles: ['adventure', 'culture'],
    bestMonths: [6, 7, 8, 12, 1, 2],
    estimatedCosts: { flightFromEurope: 200, hotelPerNight: 160, dailySpending: 100 },
    activities: [
      'Northern Lights tour',
      'Golden Circle',
      'Blue Lagoon',
      'glacier hike',
      'whale watching',
    ],
    currency: 'ISK',
    visa: 'free',
  },

  // ── Africa ──────────────────────────────────────────────────────────────────
  {
    id: 'marrakech-morocco',
    name: 'Marrakech',
    country: 'Morocco',
    countryCode: 'MA',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    continent: 'Africa',
    description:
      'A sensory explosion of spice-scented souks, pink palaces, and rooftop terraces in the Medina.',
    climate: 'semi-arid',
    travelStyles: ['city', 'culture', 'adventure'],
    bestMonths: [3, 4, 10, 11],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 60, dailySpending: 45 },
    activities: [
      'Jemaa el-Fnaa',
      'Majorelle Garden',
      'hammam',
      'Atlas Mountains day trip',
      'cooking class',
    ],
    currency: 'MAD',
    visa: 'free',
  },
  {
    id: 'cape-town-south-africa',
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    continent: 'Africa',
    description:
      "Spectacular Table Mountain towers over beaches, vineyards, and one of the world's most diverse cities.",
    climate: 'mediterranean',
    travelStyles: ['beach', 'adventure', 'city'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 650, hotelPerNight: 90, dailySpending: 55 },
    activities: [
      'Table Mountain',
      'Cape Point',
      'Boulders Beach penguins',
      'Stellenbosch wine',
      'V&A Waterfront',
    ],
    currency: 'ZAR',
    visa: 'on-arrival',
  },
  {
    id: 'zanzibar-tanzania',
    name: 'Zanzibar',
    country: 'Tanzania',
    countryCode: 'TZ',
    coordinates: { lat: -6.1659, lng: 39.2026 },
    continent: 'Africa',
    description:
      "Spice island paradise with powder-white beaches, turquoise lagoons, and Stone Town's rich history.",
    climate: 'tropical',
    travelStyles: ['beach', 'culture'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    estimatedCosts: { flightFromEurope: 700, hotelPerNight: 80, dailySpending: 50 },
    activities: [
      'Nungwi beach',
      'Stone Town tour',
      'spice tour',
      'snorkelling',
      'sunset dhow cruise',
    ],
    currency: 'TZS',
    visa: 'on-arrival',
  },
  {
    id: 'cairo-egypt',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    continent: 'Africa',
    description:
      "The Great Pyramids, Sphinx, and 5,000 years of civilisation in Africa's largest metropolis.",
    climate: 'hot desert',
    travelStyles: ['culture', 'adventure'],
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 250, hotelPerNight: 50, dailySpending: 35 },
    activities: [
      'Pyramids of Giza',
      'Egyptian Museum',
      'Khan el-Khalili bazaar',
      'Nile cruise',
      'Luxor day trip',
    ],
    currency: 'EGP',
    visa: 'on-arrival',
  },
  {
    id: 'seychelles',
    name: 'Mahé',
    country: 'Seychelles',
    countryCode: 'SC',
    coordinates: { lat: -4.6796, lng: 55.492 },
    continent: 'Africa',
    description:
      'Granite boulders, coral reefs, and pristine tropical beaches on 115 islands in the Indian Ocean.',
    climate: 'tropical',
    travelStyles: ['beach', 'adventure'],
    bestMonths: [4, 5, 10, 11],
    estimatedCosts: { flightFromEurope: 900, hotelPerNight: 200, dailySpending: 80 },
    activities: [
      'Anse Lazio beach',
      'snorkelling',
      'Vallée de Mai nature reserve',
      'sailing',
      'Creole cooking',
    ],
    currency: 'SCR',
    visa: 'free',
  },

  // ── Middle East ─────────────────────────────────────────────────────────────
  {
    id: 'dubai-uae',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    coordinates: { lat: 25.2048, lng: 55.2708 },
    continent: 'Middle East',
    description:
      'A city of superlatives — tallest skyscraper, largest mall, and unmissable luxury in the desert.',
    climate: 'hot desert',
    travelStyles: ['city', 'beach', 'culture'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 350, hotelPerNight: 140, dailySpending: 90 },
    activities: ['Burj Khalifa', 'Dubai Mall', 'desert safari', 'Palm Jumeirah', 'Dubai Frame'],
    currency: 'AED',
    visa: 'on-arrival',
  },
  {
    id: 'istanbul-turkey',
    name: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    coordinates: { lat: 41.0082, lng: 28.9784 },
    continent: 'Middle East',
    description:
      'A city straddling two continents — mosques, bazaars, Bosphorus cruises, and legendary cuisine.',
    climate: 'mediterranean',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 150, hotelPerNight: 70, dailySpending: 45 },
    activities: [
      'Hagia Sophia',
      'Grand Bazaar',
      'Topkapi Palace',
      'Bosphorus cruise',
      'Turkish bath',
    ],
    currency: 'TRY',
    visa: 'on-arrival',
  },
  {
    id: 'petra-jordan',
    name: 'Petra',
    country: 'Jordan',
    countryCode: 'JO',
    coordinates: { lat: 30.3285, lng: 35.4444 },
    continent: 'Middle East',
    description:
      'The rose-red city half as old as time — carved into sandstone cliffs by the ancient Nabataeans.',
    climate: 'hot desert',
    travelStyles: ['adventure', 'culture'],
    bestMonths: [3, 4, 10, 11],
    estimatedCosts: { flightFromEurope: 350, hotelPerNight: 60, dailySpending: 40 },
    activities: ['Treasury', 'Monastery trail', 'Siq canyon', 'Wadi Rum', 'Bedouin camp'],
    currency: 'JOD',
    visa: 'on-arrival',
  },

  // ── Asia ────────────────────────────────────────────────────────────────────
  {
    id: 'bali-indonesia',
    name: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    coordinates: { lat: -8.3405, lng: 115.092 },
    continent: 'Asia',
    description:
      'The Island of the Gods — terraced rice fields, Hindu temples, surf breaks, and legendary sunsets.',
    climate: 'tropical',
    travelStyles: ['beach', 'culture', 'adventure'],
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    estimatedCosts: { flightFromEurope: 650, hotelPerNight: 60, dailySpending: 40 },
    activities: [
      'Ubud rice terraces',
      'Tanah Lot temple',
      'Kuta surfing',
      'Monkey Forest',
      'cooking class',
    ],
    currency: 'IDR',
    visa: 'on-arrival',
  },
  {
    id: 'tokyo-japan',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    continent: 'Asia',
    description:
      "The future and the past collide in the world's greatest city — neon, ramen, robots, and Zen gardens.",
    climate: 'humid subtropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [3, 4, 5, 10, 11],
    estimatedCosts: { flightFromEurope: 750, hotelPerNight: 100, dailySpending: 80 },
    activities: [
      'Shibuya Crossing',
      'Tsukiji market',
      'Shinjuku',
      'teamLab digital art',
      'day trip to Nikko',
    ],
    currency: 'JPY',
    visa: 'free',
  },
  {
    id: 'bangkok-thailand',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    continent: 'Asia',
    description:
      'Frenetic, flavourful, and fun — temples, street food, floating markets, and epic nightlife.',
    climate: 'tropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [11, 12, 1, 2, 3],
    estimatedCosts: { flightFromEurope: 550, hotelPerNight: 50, dailySpending: 35 },
    activities: [
      'Grand Palace',
      'Wat Pho',
      'Chatuchak Market',
      'Chao Phraya river',
      'Khao San Road',
    ],
    currency: 'THB',
    visa: 'free',
  },
  {
    id: 'kyoto-japan',
    name: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    continent: 'Asia',
    description:
      "Japan's ancient capital — 1,600 Buddhist temples, geisha districts, bamboo groves, and perfect matcha.",
    climate: 'humid subtropical',
    travelStyles: ['culture', 'adventure'],
    bestMonths: [3, 4, 5, 10, 11],
    estimatedCosts: { flightFromEurope: 750, hotelPerNight: 90, dailySpending: 70 },
    activities: [
      'Fushimi Inari shrine',
      'Arashiyama bamboo',
      'Gion geisha district',
      'Kinkaku-ji',
      'tea ceremony',
    ],
    currency: 'JPY',
    visa: 'free',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    continent: 'Asia',
    description:
      'A gleaming city-state of futuristic gardens, hawker food stalls, and impeccable efficiency.',
    climate: 'tropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [2, 3, 6, 7],
    estimatedCosts: { flightFromEurope: 600, hotelPerNight: 130, dailySpending: 75 },
    activities: [
      'Gardens by the Bay',
      'Marina Bay Sands',
      'hawker centres',
      'Sentosa Island',
      'Little India',
    ],
    currency: 'SGD',
    visa: 'free',
  },
  {
    id: 'phuket-thailand',
    name: 'Phuket',
    country: 'Thailand',
    countryCode: 'TH',
    coordinates: { lat: 7.8804, lng: 98.3923 },
    continent: 'Asia',
    description:
      "Thailand's largest island offers emerald-green sea, white-sand beaches, and buzzing beach towns.",
    climate: 'tropical',
    travelStyles: ['beach', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 580, hotelPerNight: 55, dailySpending: 40 },
    activities: [
      'Patong Beach',
      'Phi Phi Islands trip',
      'Big Buddha',
      'snorkelling',
      'Phang Nga Bay',
    ],
    currency: 'THB',
    visa: 'free',
  },
  {
    id: 'chiang-mai-thailand',
    name: 'Chiang Mai',
    country: 'Thailand',
    countryCode: 'TH',
    coordinates: { lat: 18.7883, lng: 98.9853 },
    continent: 'Asia',
    description:
      "Northern Thailand's cultural heart — ancient temples, elephant sanctuaries, and jungle trekking.",
    climate: 'tropical',
    travelStyles: ['culture', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    estimatedCosts: { flightFromEurope: 580, hotelPerNight: 35, dailySpending: 30 },
    activities: [
      'Doi Inthanon National Park',
      'elephant sanctuary',
      'night bazaar',
      'Doi Suthep temple',
      'muay thai',
    ],
    currency: 'THB',
    visa: 'free',
  },
  {
    id: 'hanoi-vietnam',
    name: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    coordinates: { lat: 21.0278, lng: 105.8342 },
    continent: 'Asia',
    description:
      "Vietnam's ancient, chaotic, charming capital — French colonial architecture, pho, and Hoan Kiem Lake.",
    climate: 'subtropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 580, hotelPerNight: 40, dailySpending: 30 },
    activities: [
      'Old Quarter',
      'Hoan Kiem Lake',
      'Ho Chi Minh Mausoleum',
      'water puppet show',
      'Ha Long Bay trip',
    ],
    currency: 'VND',
    visa: 'on-arrival',
  },
  {
    id: 'maldives',
    name: 'Male Atoll',
    country: 'Maldives',
    countryCode: 'MV',
    coordinates: { lat: 4.1755, lng: 73.5093 },
    continent: 'Asia',
    description:
      'Ultra-private overwater bungalows on the bluest water on Earth — the ultimate luxury beach escape.',
    climate: 'tropical',
    travelStyles: ['beach'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 800, hotelPerNight: 350, dailySpending: 120 },
    activities: ['snorkelling', 'diving', 'sunset cruise', 'dolphin watching', 'sandbank picnic'],
    currency: 'MVR',
    visa: 'free',
  },
  {
    id: 'colombo-sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    countryCode: 'LK',
    coordinates: { lat: 7.8731, lng: 80.7718 },
    continent: 'Asia',
    description:
      'The Pearl of the Indian Ocean — ancient temples, tea plantations, leopards, and surf beaches in one island.',
    climate: 'tropical',
    travelStyles: ['beach', 'adventure', 'culture'],
    bestMonths: [12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 600, hotelPerNight: 50, dailySpending: 35 },
    activities: [
      'Sigiriya Rock Fortress',
      'tea country',
      'elephant orphanage',
      'Galle Fort',
      'surf Arugam Bay',
    ],
    currency: 'LKR',
    visa: 'on-arrival',
  },
  {
    id: 'kathmandu-nepal',
    name: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    coordinates: { lat: 27.7172, lng: 85.324 },
    continent: 'Asia',
    description:
      'Gateway to the Himalayas — ancient Durbar Squares, Everest base camp treks, and spiritual temples.',
    climate: 'subtropical highland',
    travelStyles: ['adventure', 'culture'],
    bestMonths: [3, 4, 5, 10, 11],
    estimatedCosts: { flightFromEurope: 600, hotelPerNight: 30, dailySpending: 25 },
    activities: [
      'Everest base camp trek',
      'Boudhanath Stupa',
      'Pashupatinath',
      'Swayambhunath',
      'white-water rafting',
    ],
    currency: 'NPR',
    visa: 'on-arrival',
  },
  {
    id: 'ho-chi-minh-city-vietnam',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    coordinates: { lat: 10.8231, lng: 106.6297 },
    continent: 'Asia',
    description:
      'A buzzing, traffic-filled city of street food, rooftop bars, Cu Chi Tunnels, and Mekong Delta tours.',
    climate: 'tropical',
    travelStyles: ['city', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 560, hotelPerNight: 40, dailySpending: 30 },
    activities: [
      'Cu Chi Tunnels',
      'War Remnants Museum',
      'Mekong Delta',
      'Ben Thanh Market',
      'rooftop bars',
    ],
    currency: 'VND',
    visa: 'on-arrival',
  },

  // ── Americas ─────────────────────────────────────────────────────────────────
  {
    id: 'new-york-usa',
    name: 'New York City',
    country: 'United States',
    countryCode: 'US',
    coordinates: { lat: 40.7128, lng: -74.006 },
    continent: 'Americas',
    description:
      'The city that never sleeps — iconic skyline, world-class food, Broadway, and Central Park.',
    climate: 'humid continental',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 400, hotelPerNight: 200, dailySpending: 120 },
    activities: [
      'Times Square',
      'Central Park',
      'Metropolitan Museum',
      'Brooklyn Bridge',
      'Broadway show',
    ],
    currency: 'USD',
    visa: 'on-arrival',
  },
  {
    id: 'cancun-mexico',
    name: 'Cancún',
    country: 'Mexico',
    countryCode: 'MX',
    coordinates: { lat: 21.1619, lng: -86.8515 },
    continent: 'Americas',
    description:
      "Caribbean beaches, Mayan ruins, cenote swimming, and vibrant nightlife on Mexico's Yucatán coast.",
    climate: 'tropical',
    travelStyles: ['beach', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4, 5],
    estimatedCosts: { flightFromEurope: 550, hotelPerNight: 80, dailySpending: 55 },
    activities: [
      'Chichen Itza',
      'cenote diving',
      'Tulum ruins',
      'snorkelling Cozumel',
      'Isla Mujeres',
    ],
    currency: 'MXN',
    visa: 'free',
  },
  {
    id: 'rio-de-janeiro-brazil',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    coordinates: { lat: -22.9068, lng: -43.1729 },
    continent: 'Americas',
    description:
      'Cristo Redentor, Carnival, samba, Ipanema beach — the Marvelous City delivers on all fronts.',
    climate: 'tropical',
    travelStyles: ['beach', 'city', 'culture'],
    bestMonths: [12, 1, 2, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 700, hotelPerNight: 80, dailySpending: 55 },
    activities: [
      'Christ the Redeemer',
      'Sugarloaf Mountain',
      'Ipanema beach',
      'Lapa nightlife',
      'favela tour',
    ],
    currency: 'BRL',
    visa: 'free',
  },
  {
    id: 'buenos-aires-argentina',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    continent: 'Americas',
    description:
      'The Paris of South America — tango, steak, art deco architecture, and electric football culture.',
    climate: 'humid subtropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [10, 11, 12, 3, 4],
    estimatedCosts: { flightFromEurope: 800, hotelPerNight: 70, dailySpending: 45 },
    activities: [
      'La Boca neighbourhood',
      'tango show',
      'Palermo bars',
      'La Recoleta Cemetery',
      'steak dinner',
    ],
    currency: 'ARS',
    visa: 'free',
  },
  {
    id: 'cusco-peru',
    name: 'Cusco & Machu Picchu',
    country: 'Peru',
    countryCode: 'PE',
    coordinates: { lat: -13.5226, lng: -71.9674 },
    continent: 'Americas',
    description:
      'The historic capital of the Inca Empire, and gateway to the iconic Machu Picchu citadel in the clouds.',
    climate: 'subtropical highland',
    travelStyles: ['adventure', 'culture'],
    bestMonths: [5, 6, 7, 8, 9],
    estimatedCosts: { flightFromEurope: 750, hotelPerNight: 60, dailySpending: 40 },
    activities: [
      'Machu Picchu',
      'Inca Trail',
      'Sacred Valley',
      'San Pedro Market',
      'Rainbow Mountain',
    ],
    currency: 'PEN',
    visa: 'free',
  },
  {
    id: 'havana-cuba',
    name: 'Havana',
    country: 'Cuba',
    countryCode: 'CU',
    coordinates: { lat: 23.1136, lng: -82.3666 },
    continent: 'Americas',
    description:
      'Frozen in time — classic American cars, crumbling colonial facades, rum cocktails, and live salsa.',
    climate: 'tropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 600, hotelPerNight: 60, dailySpending: 40 },
    activities: [
      'Malecón promenade',
      "Hemingway's Bar",
      'classic car tour',
      'Viñales Valley',
      'salsa class',
    ],
    currency: 'CUP',
    visa: 'on-arrival',
  },
  {
    id: 'costa-rica',
    name: 'Costa Rica',
    country: 'Costa Rica',
    countryCode: 'CR',
    coordinates: { lat: 9.7489, lng: -83.7534 },
    continent: 'Americas',
    description:
      'Pura vida! Rainforests, volcanoes, sloths, world-class surfing, and eco-adventure all in one country.',
    climate: 'tropical',
    travelStyles: ['adventure', 'beach'],
    bestMonths: [12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 650, hotelPerNight: 80, dailySpending: 55 },
    activities: [
      'Arenal Volcano',
      'Manuel Antonio beach',
      'zip-lining',
      'sloth sanctuary',
      'surfing Tamarindo',
    ],
    currency: 'CRC',
    visa: 'free',
  },
  {
    id: 'new-orleans-usa',
    name: 'New Orleans',
    country: 'United States',
    countryCode: 'US',
    coordinates: { lat: 29.9511, lng: -90.0715 },
    continent: 'Americas',
    description:
      'Jazz, Cajun food, Mardi Gras, and the most unique cultural blend in North America — the Big Easy.',
    climate: 'humid subtropical',
    travelStyles: ['city', 'culture'],
    bestMonths: [2, 3, 4, 10, 11],
    estimatedCosts: { flightFromEurope: 500, hotelPerNight: 130, dailySpending: 90 },
    activities: ['French Quarter', 'Bourbon Street', 'jazz clubs', 'Mardi Gras', 'swamp tour'],
    currency: 'USD',
    visa: 'on-arrival',
  },
  {
    id: 'vancouver-canada',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    coordinates: { lat: 49.2827, lng: -123.1207 },
    continent: 'Americas',
    description:
      'Mountains meet ocean in this cosmopolitan Pacific city — skiing, kayaking, and sushi-world-class dining.',
    climate: 'oceanic',
    travelStyles: ['city', 'adventure'],
    bestMonths: [6, 7, 8, 9],
    estimatedCosts: { flightFromEurope: 550, hotelPerNight: 160, dailySpending: 100 },
    activities: [
      'Stanley Park',
      'Granville Island',
      'Whistler ski resort',
      'sea kayaking',
      'Capilano Suspension Bridge',
    ],
    currency: 'CAD',
    visa: 'on-arrival',
  },
  {
    id: 'patagonia-argentina',
    name: 'Patagonia',
    country: 'Argentina',
    countryCode: 'AR',
    coordinates: { lat: -51.623, lng: -69.2168 },
    continent: 'Americas',
    description:
      'The end of the world — dramatic spires, glaciers calving into turquoise lakes, condors, and silence.',
    climate: 'cold desert',
    travelStyles: ['adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    estimatedCosts: { flightFromEurope: 900, hotelPerNight: 90, dailySpending: 60 },
    activities: [
      'Torres del Paine trek',
      'Perito Moreno Glacier',
      'condor spotting',
      'kayaking',
      'estancia stay',
    ],
    currency: 'ARS',
    visa: 'free',
  },
  {
    id: 'cartagena-colombia',
    name: 'Cartagena',
    country: 'Colombia',
    countryCode: 'CO',
    coordinates: { lat: 10.391, lng: -75.4794 },
    continent: 'Americas',
    description:
      'A UNESCO-listed colonial walled city on the Caribbean coast — colourful, sensual, and endlessly photogenic.',
    climate: 'tropical',
    travelStyles: ['beach', 'culture', 'city'],
    bestMonths: [12, 1, 2, 3, 4],
    estimatedCosts: { flightFromEurope: 700, hotelPerNight: 70, dailySpending: 45 },
    activities: [
      'Walled City',
      'Rosario Islands',
      'street food tour',
      'salsa dancing',
      'Castillo San Felipe',
    ],
    currency: 'COP',
    visa: 'free',
  },

  // ── Oceania ──────────────────────────────────────────────────────────────────
  {
    id: 'sydney-australia',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    continent: 'Oceania',
    description:
      'Bondi Beach, Opera House, harbour cruises, and a cafe culture that rivals any city on Earth.',
    climate: 'humid subtropical',
    travelStyles: ['beach', 'city', 'culture'],
    bestMonths: [9, 10, 11, 12, 3, 4],
    estimatedCosts: { flightFromEurope: 1100, hotelPerNight: 150, dailySpending: 100 },
    activities: [
      'Sydney Opera House',
      'Bondi Beach',
      'harbour bridge climb',
      'Taronga Zoo',
      'Blue Mountains',
    ],
    currency: 'AUD',
    visa: 'required',
  },
  {
    id: 'bora-bora-french-polynesia',
    name: 'Bora Bora',
    country: 'French Polynesia',
    countryCode: 'PF',
    coordinates: { lat: -16.5004, lng: -151.7415 },
    continent: 'Oceania',
    description:
      "A dormant volcano ringed by a turquoise lagoon and a coral reef — arguably the world's most beautiful island.",
    climate: 'tropical',
    travelStyles: ['beach'],
    bestMonths: [5, 6, 7, 8, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 1500, hotelPerNight: 500, dailySpending: 150 },
    activities: [
      'overwater bungalow',
      'lagoon snorkelling',
      'shark feeding',
      'jet ski safari',
      'sunset cruise',
    ],
    currency: 'XPF',
    visa: 'free',
  },
  {
    id: 'queenstown-new-zealand',
    name: 'Queenstown',
    country: 'New Zealand',
    countryCode: 'NZ',
    coordinates: { lat: -45.0312, lng: 168.6626 },
    continent: 'Oceania',
    description:
      'The adventure capital of the world — bungee jumping, skiing, paragliding, and jaw-dropping fjords.',
    climate: 'oceanic',
    travelStyles: ['adventure'],
    bestMonths: [12, 1, 2, 6, 7, 8],
    estimatedCosts: { flightFromEurope: 1200, hotelPerNight: 130, dailySpending: 90 },
    activities: [
      'bungee jumping',
      'Milford Sound cruise',
      'skiing',
      'paragliding',
      'Lord of the Rings tour',
    ],
    currency: 'NZD',
    visa: 'on-arrival',
  },
  {
    id: 'fiji',
    name: 'Fiji',
    country: 'Fiji',
    countryCode: 'FJ',
    coordinates: { lat: -17.7134, lng: 178.065 },
    continent: 'Oceania',
    description:
      'The "soft coral capital of the world" — 330 islands of tropical paradise with legendary Fijian warmth.',
    climate: 'tropical',
    travelStyles: ['beach', 'adventure'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    estimatedCosts: { flightFromEurope: 1200, hotelPerNight: 120, dailySpending: 70 },
    activities: [
      'coral reef diving',
      'village visits',
      'island hopping',
      'kayaking',
      'kava ceremony',
    ],
    currency: 'FJD',
    visa: 'free',
  },

  // ── More diverse picks ──────────────────────────────────────────────────────
  {
    id: 'tbilisi-georgia',
    name: 'Tbilisi',
    country: 'Georgia',
    countryCode: 'GE',
    coordinates: { lat: 41.7151, lng: 44.8271 },
    continent: 'Europe',
    description:
      'A hidden gem at the crossroads of Europe and Asia — ancient baths, natural wine, and the Caucasus mountains.',
    climate: 'continental',
    travelStyles: ['city', 'culture', 'adventure'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 150, hotelPerNight: 50, dailySpending: 35 },
    activities: [
      'Narikala fortress',
      'sulphur baths',
      'Old Town',
      'Kazbegi mountains',
      'Georgian wine tasting',
    ],
    currency: 'GEL',
    visa: 'free',
  },
  {
    id: 'valletta-malta',
    name: 'Valletta',
    country: 'Malta',
    countryCode: 'MT',
    coordinates: { lat: 35.8997, lng: 14.5147 },
    continent: 'Europe',
    description:
      'A tiny Baroque capital on a limestone island — crystal-clear lagoons, Knights Templar history, and sun year-round.',
    climate: 'mediterranean',
    travelStyles: ['culture', 'beach', 'city'],
    bestMonths: [4, 5, 6, 9, 10, 11],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 80, dailySpending: 55 },
    activities: [
      'Blue Lagoon',
      'Valletta Baroque walk',
      'Mdina',
      'cliff diving',
      "St. John's Co-Cathedral",
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'medellín-colombia',
    name: 'Medellín',
    country: 'Colombia',
    countryCode: 'CO',
    coordinates: { lat: 6.2476, lng: -75.5658 },
    continent: 'Americas',
    description:
      'City of Eternal Spring — innovative urban cable cars, vibrant street art, flower festivals, and warm locals.',
    climate: 'subtropical highland',
    travelStyles: ['city', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 6, 7, 8],
    estimatedCosts: { flightFromEurope: 720, hotelPerNight: 55, dailySpending: 35 },
    activities: [
      'cable car to Arví Park',
      'Botero sculptures',
      'El Poblado nightlife',
      'flower festival',
      'coffee farm',
    ],
    currency: 'COP',
    visa: 'free',
  },
  {
    id: 'luang-prabang-laos',
    name: 'Luang Prabang',
    country: 'Laos',
    countryCode: 'LA',
    coordinates: { lat: 19.8833, lng: 102.1347 },
    continent: 'Asia',
    description:
      'A tranquil UNESCO city of golden temples, saffron-robed monks, and the Mekong River — Southeast Asia at its most serene.',
    climate: 'tropical',
    travelStyles: ['culture', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    estimatedCosts: { flightFromEurope: 600, hotelPerNight: 35, dailySpending: 25 },
    activities: [
      'alms giving ceremony',
      'Kuang Si Waterfall',
      'Mekong sunset cruise',
      'night market',
      'Mount Phousi',
    ],
    currency: 'LAK',
    visa: 'on-arrival',
  },
  {
    id: 'muscat-oman',
    name: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    coordinates: { lat: 23.588, lng: 58.3829 },
    continent: 'Middle East',
    description:
      'A sophisticated, safe, and deeply welcoming Gulf nation — pristine wadis, desert camping, and stunning forts.',
    climate: 'hot desert',
    travelStyles: ['culture', 'adventure'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    estimatedCosts: { flightFromEurope: 400, hotelPerNight: 90, dailySpending: 60 },
    activities: [
      'Sultan Qaboos Grand Mosque',
      'Wahiba Sands desert',
      'wadi bashing',
      'Nizwa Fort',
      'snorkelling',
    ],
    currency: 'OMR',
    visa: 'on-arrival',
  },
  {
    id: 'trinidad-and-tobago',
    name: 'Trinidad & Tobago',
    country: 'Trinidad and Tobago',
    countryCode: 'TT',
    coordinates: { lat: 10.6918, lng: -61.2225 },
    continent: 'Americas',
    description:
      'The birthplace of steelpan and soca — a Caribbean twin island with rainforests, leatherback turtles, and Carnival madness.',
    climate: 'tropical',
    travelStyles: ['beach', 'culture', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5],
    estimatedCosts: { flightFromEurope: 750, hotelPerNight: 90, dailySpending: 55 },
    activities: [
      'Carnival',
      'leatherback turtle nesting',
      'bird watching',
      'Pigeon Point beach',
      'steel band show',
    ],
    currency: 'TTD',
    visa: 'free',
  },
  {
    id: 'porto-portugal',
    name: 'Porto',
    country: 'Portugal',
    countryCode: 'PT',
    coordinates: { lat: 41.1579, lng: -8.6291 },
    continent: 'Europe',
    description:
      'Port wine, tiled façades, dramatic bridges, and the most beautiful bookshop in the world.',
    climate: 'mediterranean',
    travelStyles: ['city', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    estimatedCosts: { flightFromEurope: 90, hotelPerNight: 80, dailySpending: 60 },
    activities: [
      'Ribeira waterfront',
      'port wine lodges',
      'Livraria Lello',
      'Dom Luís Bridge',
      'Foz do Douro beach',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'seville-spain',
    name: 'Seville',
    country: 'Spain',
    countryCode: 'ES',
    coordinates: { lat: 37.3891, lng: -5.9845 },
    continent: 'Europe',
    description:
      'Flamenco, tapas, orange trees, and the most exuberant Easter and April Fair celebrations on Earth.',
    climate: 'mediterranean',
    travelStyles: ['city', 'culture'],
    bestMonths: [3, 4, 5, 10, 11],
    estimatedCosts: { flightFromEurope: 100, hotelPerNight: 90, dailySpending: 60 },
    activities: [
      'Real Alcázar',
      'Giralda tower',
      'flamenco show',
      'tapas bar crawl',
      'Plaza de España',
    ],
    currency: 'EUR',
    visa: 'free',
  },
  {
    id: 'las-vegas-usa',
    name: 'Las Vegas',
    country: 'United States',
    countryCode: 'US',
    coordinates: { lat: 36.1699, lng: -115.1398 },
    continent: 'Americas',
    description:
      'The Entertainment Capital of the World — casinos, shows, grand canyon day trips, and non-stop excess.',
    climate: 'hot desert',
    travelStyles: ['city', 'adventure'],
    bestMonths: [3, 4, 10, 11],
    estimatedCosts: { flightFromEurope: 450, hotelPerNight: 100, dailySpending: 120 },
    activities: [
      'The Strip',
      'Grand Canyon',
      'Cirque du Soleil',
      'Fremont Street',
      'helicopter tour',
    ],
    currency: 'USD',
    visa: 'on-arrival',
  },
]

/** Total number of destinations in the database */
export const DESTINATION_COUNT = destinations.length

/** All valid travel styles */
export const TRAVEL_STYLES: TravelStyle[] = ['beach', 'city', 'adventure', 'culture']

/** All valid continents */
export const CONTINENTS: Continent[] = [
  'Europe',
  'Africa',
  'Asia',
  'Americas',
  'Oceania',
  'Middle East',
]
